// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"time"
)

type Filmmaker struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Dob       time.Time `json:"dob"`
	CreatedAt time.Time `json:"created_at"`
}

type Movie struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Year      int32     `json:"year"`
	CreatedAt time.Time `json:"created_at"`
}

type MovieCredit struct {
	ID          int64     `json:"id"`
	FilmmakerID int64     `json:"filmmaker_id"`
	MovieID     int64     `json:"movie_id"`
	RoleID      int64     `json:"role_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type Role struct {
	ID int64 `json:"id"`
	// director, actor, etc
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}
